spring.application.name=person-service

#PostgreSQL by aiven.io
spring.datasource.url=jdbc:postgresql://cohort46fs-eddfish.c.aivencloud.com:22423/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=${AIVEN_PASS}

#JPA Hibernate
spring.jpa.hibernate.ddl-auto=update
#Dev mode
spring.jpa.show-sql=true
